### PR TITLE
id:21288 Patch PG JDBC driver version 9.4.1206.

### PR DESCRIPTION
**Pull request by mtsay-comprehend**
### All Submissions:

* [x] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
  - read the guidelines, didn't bother checking whether I followed them.
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
  - there are no other open PRs

### New Feature Submissions:

1. [x] Does your submission pass tests?
  - yes
2. [x] Does mvn checkstyle:check pass ?
  - this branch is still using ant and I have verified that `checkstyle` ( or anything similar ) is absent in `build.xml`.

### Changes to Existing Features:

* [x] Does this break existing behaviour? If so please explain.
  - changes are guarded by a version check.
* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
  - see associated TP.
* [x] Have you written new tests for your core changes, as applicable?
  - test was updated in an earlier commit and then later reverted.
* [x] Have you successfully run tests with your changes locally?
  - tests succeeded against locally running PG 10.5 and PG 9.4 DBs.

### CODE REVIEW

**Comment by NikolaySokolov** [comment]
Where did you built it to verify it works? 

Ideally, since it's our fork and we want to make sure we are not introducing anything unexpected into the resulting binary, I'd prefer you do a Dockerfile with all dependencies installed, build it inside it and add it to PR as well. At very least - please put all steps which you've followed into TP.

**Comment by rivanov-comprehend** [comment]
@mtsay-comprehend , please remove from PR description all that mess, we are not potgressql team, we do not need this details. They just confuse.

please answer my question from original PR (https://github.com/comprehend/panacea/pull/907#pullrequestreview-173577224).

> And now please define who are "we" and define whole list decisions and options that you considered.

----

please explain why fork is the only way to resolve a problem? We need all details !
If it is too long story - give us call. 

FYI: Forking jdbc driver today and next day forking java just to resolve some problems is not goo approach.

**Comment by rivanov-comprehend** [comment]
https://github.com/pgjdbc/pgjdbc/commit/c9e5fc8bf53ead845f7b56c9cbe3c1058b636ca5
is release in REL9.4.1209 .

did you tested 1209  version ? if 1212 is not ok for us , reasons you still need to share.

**Comment by NikolaySokolov** [comment]
Both commits are in fact part of 9.4.1209

**Comment by mtsay-comprehend** [comment]
We've decided against taking this approach and chose a different option instead. Hence I'm closing this TP.

**Pull request closed without merging**
